name: downscaling-hires
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=2.2.6
  - scipy=1.15.3
  - pandas=2.3.3
  - matplotlib=3.10.9
  - xarray=2025.6.1
  - zarr=2.18.3
  - netcdf4=1.7.4
  - tensorboard=2.20.0
  - pillow
  - pytorch=2.11.0
  - pytorch-cuda=12.8
  - pip:
      - diffusers==0.38.0
